name: presensi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.3
  geolocator: ^14.0.2
  intl: ^0.20.2

  google_mlkit_face_detection: ^0.13.1
  # google_maps_flutter: ^2.7.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0

  tflite_flutter: ^0.12.1
  image: ^4.1.3

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.3

  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/models/mobilefacenet.tflite
    - assets/logo/logo_aplikasi_presensi.png

